stages:
  - docker-build-env
  - docker-build
  - docker-test

docker-build-env:
  stage: docker-build-env
  variables:
    dockerfile: docker/nektar-env/Dockerfile
    image_name: nektar-env
  tags:
    - shell
  only:
    refs:
      - feature/gitlab_ci
      - /^docker\/.*$/
      - tags
  script:
    - docker build --cpu-period 100000 --cpu-quota 200000 -t ${image_name} -f ${dockerfile} .

docker-build:
  stage: docker-build
  image: nektar-env
  only:
    refs:
      - feature/gitlab_ci
      - /^docker\/.*$/
      - tags
  script:
    - mkdir ~/.ccache && echo "cache_dir = /cache/nektar" >> ~/.ccache/ccache.conf
    - mkdir build && (cd build &&
      cmake
      -DCMAKE_BUILD_TYPE:STRING=Debug
      -DNEKTAR_FULL_DEBUG:BOOL=ON
      -DNEKTAR_TEST_ALL:BOOL=ON
      -DNEKTAR_BUILD_TIMINGS:BOOL=ON
      -DNEKTAR_USE_ARPACK:BOOL=ON
      -DNEKTAR_USE_FFTW:BOOL=ON
      -DNEKTAR_USE_MPI:BOOL=ON
      -DNEKTAR_USE_SCOTCH:BOOL=ON
      -DNEKTAR_USE_PETSC:BOOL=ON
      -DNEKTAR_USE_HDF5:BOOL=ON
      -DNEKTAR_USE_MESHGEN:BOOL=ON
      -DNEKTAR_USE_CCM:BOOL=ON
      -DNEKTAR_BUILD_PYTHON:BOOL=ON
      -DNEKTAR_TEST_USE_HOSTFILE=ON
      -DNEKTAR_ERROR_ON_WARNINGS=OFF
      .. &&
      make -j 2)
    - tar -czf build.tar.gz --exclude="*.o" build
  artifacts:
    paths:
      - build.tar.gz

docker-test:
  stage: docker-test
  image: nektar-environment
  dependencies:
    - docker-build
  script:
    - tar xf build.tar.gz
    - cd build && ctest -j 2
