stages:
  - docker-build-env

docker-build-env:
  stage: docker-build-env
  variables:
    dockerfile: docker/nektar-env/Dockerfile
    image_name: nektarpp/nektar-env
  tags:
    - shell
  only:
    refs:
      - feature/gitlab_ci
      - /^docker\/.*$/
      - tags
  script:
    - docker build --cpu-period 100000 --cpu-quota 200000 -t ${image_name} -f ${dockerfile} .
